config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user

  def previous
    self.class.where("id < #{self.id}").order("id desc").first
  end

  def next
    self.class.where("id > #{self.id}").order("id asc").first
  end

  def to_s
    "#{self.first_name} #{self.last_name}"
  end

end

app/models/prospect.rb
class Prospect < ApplicationRecord
  def previous
    self.class.where("id < #{self.id}").order("id desc").first
  end

  def next
    self.class.where("id > #{self.id}").order("id asc").first
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :vip, :admin]

  after_initialize :set_default_role, :if => :new_record?
  validates_presence_of :email

  has_many :contacts

  def set_default_role
    self.role ||= :user
  end

  def to_s
    "#{self.name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user!
  before_action :redirect_cancel, only: [:create, :update]

  def create
    params.permit!
    @contact = Contact.new(params[:contact])
    @contact.user_id = current_user.id
    if @contact.save
      flash[:notice] = "Contact was successfully created!"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    validate_user
  end

  def index
    @contacts = Contact.all.where(user_id: current_user)
  end

  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
    validate_user
  end

  def update
    params.permit!
    @contact = Contact.find(params[:id])

    if params[:contact]
      if @contact.update_attributes(params[:contact])
        flash[:notice] = "Contact was successfully updated!"
        redirect_to :action => :show, :id => @contact and return
      else
        render :action => :edit and return
      end
    end
  end

  private

  def redirect_cancel
    redirect_to(action: :show, id: params[:id]) if params[:commit] == "Cancel" && params[:id]
    redirect_to(action: :index)
  end

  def validate_user
    if @contact.user_id != current_user.id
      flash[:error] = "There is no contact with that Id"
      redirect_to action: :index and return
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :redirect_cancel, only: [:create, :update]

  def edit
    @user = User.find(params[:id])
  end

  def index
    redirect_to action: :show, id: current_user.id unless current_user.try(:admin?)
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def update
    params.permit!
    @user = User.find(params[:id])

    if params[:user]
      if @user.update_attributes(params[:user])
        flash[:notice] = "User was successfully updated!"
        redirect_to :action => :show, :id => @user and return
      else
        render :action => :edit and return
      end
    end
  end

  private

  def redirect_cancel
    redirect_to(action: :show, id: params[:id]) if params[:commit] == "Cancel"
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.slim
td.uk-table-link
  = link_to contact.id, contact
td
  = contact.first_name
td
  = contact.last_name
td
  = contact.email
td
  = contact.nickname
td
  = contact.note

app/views/contacts/_contact_hz.html.slim
td.uk-table-link
  = link_to contact.first_name, contact
td
  = contact.last_name
td
  = contact.email
td
  = contact.nickname
td
  = contact.address
td
  = contact.city
td
  = contact.state
td
  = contact.zip
td
  = contact.note

app/views/contacts/_contact_hz_hd.html.slim
th
  | First Name
th
  | Last Name
th.uk-table-shrink
  | Email
th.uk-table-shrink
  | Nickname / Salutation
th
  | Address
th
  | City
th.uk-table-shrink
  | State
th.uk-table-shrink
  | Zip
th.uk-table-expand
  | Note

app/views/contacts/_contact_vt.html.slim
tr
  th.uk-table-shrink
    | First&nbsp;Name&nbsp;:
  td
    = contact.first_name.nil? ? "No First Name Provided" : contact.first_name
tr
  th
    | Last&nbsp;Name&nbsp;:
  td
    = contact.last_name.nil? ? "No Last Name Provided" : contact.last_name
tr
  th
    | Email&nbsp;:
  td
    = contact.email if contact.email
tr
  th
    | Nickname/Salutation&nbsp;:
  td
    = contact.nickname if contact.nickname
tr
  th
    | Address&nbsp;:
  td
    = contact.address
tr
  th
    | City&nbsp;:
  td
    = contact.city
tr
  th
    | State&nbsp;:
  td
    = contact.state
tr
  th
    | Zip&nbsp;:
  td
    = contact.zip
tr
  th
    | Note&nbsp;:
  td
    = contact.note? ? contact.note : "No notes yet."
tr
  th
    | Actions&nbsp;:
  td
    = link_to "Edit", edit_contact_path(contact)

app/views/contacts/_form.html.slim
- if contact.errors.any?
  .error_explanation
    .uk-alert *{class: "uk-alert-danger"}
      | #{pluralize(contact.errors.count, "error")} prohibited this Game from being saved:
      ul
        - contact.errors.full_messages.each do |msg|
          li
            = msg

= form_with(model: contact, local: true, html: {class: "uk-form-horizontal"}) do |form|
  .uk-margin
    label.uk-form-label for="first_name"
      | First Name :
    .uk-form-controls
      = form.text_field :first_name, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="last_name"
      | Last Name :
    .uk-form-controls
      = form.text_field :last_name, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="email"
      | Email:
    .uk-form-controls
      = form.text_field :email, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="nickname"
      | Nickname/Salutation :
    .uk-form-controls
      = form.text_field :nickname, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="address"
      | Address :
    .uk-form-controls
      = form.text_field :address, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="city"
      | City :
    .uk-form-controls
      = form.text_field :city, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="state"
      | State :
    .uk-form-controls
      = form.text_field :state, {class: "uk-input uk-form-width-small"}
  .uk-margin
    label.uk-form-label for="zip"
      | Zip :
    .uk-form-controls
      = form.text_field :zip, {class: "uk-input uk-form-width-small"}
  .uk-margin
    label.uk-form-label for="note"
      | Note :
    .uk-form-controls
      = form.text_area(:note, rows: 5, class: "uk-textarea uk-form-width-large")
  .uk-margin
    .uk-form-controls
      .uk-flex *{class: ["uk-flex-bottom uk-text-center"]}
        .
          = form.submit "Save", class: "uk-button uk-button-primary"
        .uk-margin-left
          = form.submit "Cancel", class: "uk-button uk-button-secondary uk-button-small"

app/views/contacts/edit.html.slim
h3
  | Editing #{params[:controller].singularize.titleize} "#{@contact.to_s}"
== render "form", contact: @contact

app/views/contacts/index.html.slim
.uk-container *{class: ["uk-container-center"]}
  .uk-flex *{class: ["uk-flex-between"]}
    .
      h3 All Contacts
    .
      = link_to "Add a Contact", new_contact_path, class: "uk-button uk-button-primary uk-button-small"
  - if @contacts.any?
    table#contacts class="uk-table uk-table-divider uk-table-striped uk-table-hover"
      thead
        == render "contact_hz_hd"
      tbody
        - @contacts.each do |contact|
          tr
            == render "contact_hz", contact: contact
  - else
    p You don't have any contacts yet.

app/views/contacts/new.html.slim
h3
  | Creating a new #{params[:controller].singularize.titleize}
== render "form", contact: @contact

app/views/contacts/show.html.slim
h3
  | Showing Contact "#{@contact}"
  p
  table#contact class="uk-table uk-table-divider uk-table-striped uk-table-hover uk-table-small"
    == render "contact_vt", contact: @contact
  p
    = @contact.previous.nil? ? "Previous" : link_to("Previous", @contact.previous)
    |&nbsp;|&nbsp;
    = @contact.next.nil? ? "Next" : link_to("Next", @contact.next)

app/views/layouts/_messages.html.slim
/ Rails flash messages
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .uk-alert *{class: ["uk-alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"]}
      p #{msg}

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Realtors', users_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.slim
nav.uk-navbar-container uk-navbar="boundary-align: true; align: center;"
  .uk-navbar-left
    a uk-icon="icon: home" href="/"
    ul.uk-navbar-nav
      li.uk-active
        = link_to "Contacts", contacts_path
  .uk-navbar-right
    ul.uk-navbar-nav
      - if current_user.try(:admin?)
        li
          = link_to "Realtors", users_path
      - if user_signed_in?
        li
          = link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Reelatr'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Reelatr'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    .uk-container *{class: ["uk-container-medium"]}
      == render 'layouts/navigation'
      .uk-section *{class: ["uk-section-default uk-section-small"]}
        .uk-vertical-align-top
          == render 'layouts/messages'
          == yield
      .uk-section *{class: ["uk-section-muted uk-section-xsmall"]}
        .uk-text-center
          .uk-vertical-align-middle
            p
              | Version 1 :: Copyright 2018 :: <a href="http://www.ngzax.com">Daryl Richter</a> :: All Rights Reserved.

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/prospects/index.html.slim
.uk-container *{class: ["uk-container-center"]}
  h3
    | All Prospects
    - if @prospects.any?
      table#prospects class="uk-table uk-table-divider uk-table-striped uk-table-hover"
        thead
          th
            | Id
          th
            | First Name
          th
            | Last Name
          th.uk-table-shrink
            | Email
          th.uk-table-shrink
            | Nickname / Salutation
          th.uk-table-expand
            | Note
        tbody
          - @prospects.each do |prospect|
            tr
              == render prospect

app/views/users/_user.html.slim
td
  = link_to user.id, user
td
  = user.name
td
  = user.email

app/views/users/_user_h.html.slim
tr
  th
    | Name :
  td
    = user.name.nil? ? "No Name Provided" : user.name
tr
  th
    | Email :
  td
    = user.email if @user.email

app/views/users/_user_hz.html.slim
td
  = link_to user.id, user
td
  = user.name
td
  = user.email

app/views/users/_user_hz_hd.html.slim
th
  | Id
th
  | Name
th
  | Email

app/views/users/_user_v.html.slim
td
  = link_to user.id, user
td
  = user.name
td
  = user.email

app/views/users/_user_v_h.html.slim
th
  | Id
th
  | Name
th
  | Email

app/views/users/_user_vt.html.slim
tr
  th.uk-table-shrink
    | Name :
  td.uk-table-shrink
    = user.name.nil? ? "No Name Provided" : user.name
tr
  th
    | Email&nbsp;:
  td
    = user.email if user.email
tr
  th
    | Actions&nbsp;:
  td
    = link_to "Edit", edit_user_path(user)

app/views/users/edit.html.slim
h3
  | Editing #{params[:controller].singularize.titleize} "#{@user.to_s}"
= form_with(model: @user, local: true, html: {class: "uk-form-horizontal"}) do |form|
  .uk-margin
    label.uk-form-label for="name"
      | Name:
    .uk-form-controls
      = form.text_field :name, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    label.uk-form-label for="email"
      | Email:
    .uk-form-controls
      = form.text_field :email, {class: "uk-input uk-form-width-medium"}
  .uk-margin
    .uk-form-controls
      .uk-flex *{class: ["uk-flex-bottom uk-text-center"]}
        .
          = form.submit "Save", class: "uk-button uk-button-primary"
        .uk-margin-left
          = form.submit "Cancel", class: "uk-button uk-button-secondary uk-button-small"

app/views/users/index.html.slim
.uk-container *{class: ["uk-container-center"]}
  h3
    | All Realtors
    - if @users.any?
      table#users class="uk-table uk-table-divider uk-table-striped uk-table-hover"
        thead
          == render "user_hz_hd"
        tbody
          - @users.each do |user|
            tr
              == render "user_hz", user: user

app/views/users/show.html.slim
h3
  | Showing Realtor ##{@user.id}
  p
  .uk-container
    table#user class="uk-table uk-table-divider uk-table-striped uk-table-hover uk-table-small"
      == render "user_vt", user: @user

app/views/visitors/index.html.slim
h3
  | Welcome to Reelatr.com
h5
  | Your Real Estate Contact Management Solution
p
  | There are currently #{User.count} registered realtors.
- unless current_user
  p
    | Are you one of them?
    = link_to " Please Sign In", new_user_session_path
  p
    | If you're not but would like to be:
    = link_to " Sign up", new_registration_path(User)